### ISSUE TITLE
Support for lower 2 canvases

### ISSUE THREAD

**Issue by rushiiMachine** [smirea/reddit-place-bot#4]
Reddit just extended to lower 2 canvases, looks like fetching canvas + canvasIndex is broken

Edit: it appears canvas.codes has not yet updated, I've sent them a notification email

**Comment by smirea** [comment]
yep, it's actually supported right now, it just can't check to see if it's overwriting the same pixel. less efficient but still functional

**Comment by diffficult** [comment]
getting `error Command failed with signal "SIGSEGV".` when trying to run it, don't know if it is related to the extended canvas. I was trying to draw something small on the pre existing one though.

**Comment by smirea** [comment]
ok updated with new api and 4 canvases
